name: build windows

on: [ push ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 14.0.0

      - name: install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          mvn clean install -DskipTests

      - name: jlink
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          mvn javafx:jlink

      - name: jpackage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          jpackage --input target --name JXClipboard --main-jar JXClipboard-0.7.jar --main-class de.ruegnerlukas.jxclipboard.JXClipboard --type msi --dest target --win-dir-chooser --win-menu --win-shortcut

      - uses: actions/upload-artifact@v2
        with:
          name: artifact-win
          path: target/
          retention-days: 2