name: build

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11.0.5
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.5

      - name: install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          mvn clean install -DskipTests

      - name: jlink
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          mvn javafx:jlink
        with:
          name: created zip
          path: target/JXClipboard.zip